import { getLocalRecipes } from './localRecipes';

const items = [
    {
        id: 1,
        isLocal: false,
        name: 'American Burger',
        description: 'A delicious and juicy burger perfect for any occasion.',
        timeToCook: '30 mins',
        serves: 2,
        image: '/american_burger.png',
        ingredients: [
            'Ground chicken : 500g',
            'Burger buns : 4',
            'Lettuce leaves : 4-6',
            'Tomato slices : 6-8',
            'Cheddar cheese : 4 slices',
            'Salt : 1 tsp',
            'Black pepper : 1 tsp',
            'Paprika : 1 tsp',
            'Butter : 2 tbsp',
            'Ketchup/Mayo/Mustard : as required',
        ],
        steps: [
            'Mix ground chicken with salt, pepper, and paprika in a bowl.',
            'Divide into equal portions and shape into patties.',
            'Heat a skillet or grill and cook patties for 4-5 minutes per side.',
            'Place cheese slices over patties and let them melt.',
            'Slice and butter the burger buns.',
            'Toast the buns on a skillet until lightly golden.',
            'Layer lettuce and tomato slices on the bottom bun.',
            'Place the cooked cheese patty on top.',
            'Add ketchup, mayo, or mustard as desired.',
            'Cover with the top bun and serve immediately.',
        ],
    },

    {
        id: 2,
        isLocal: false,
        name: 'Rice Idli',
        description: 'A traditional South Indian steamed breakfast made using fermented batter.',
        timeToCook: '20 mins',
        serves: 4,
        image: '/rice_idli.png',
        ingredients: [
            'Rice : 2 cups',
            'Urad dal : 1 cup',
            'Salt : 1-2 tsp',
            'Oil : 1 tbsp for greasing',
            'Water : as required',
        ],
        steps: [
            'Soak rice and urad dal separately for 4-6 hours.',
            'Grind urad dal into a smooth fluffy batter.',
            'Grind rice into a slightly coarse batter.',
            'Mix both batters with salt and ferment overnight.',
            'Grease idli plates lightly with oil.',
            'Pour fermented batter into molds.',
            'Steam for 10-12 minutes on medium flame.',
            'Allow to cool for 2 minutes before removing.',
            'Serve warm with coconut chutney.',
            'Enjoy with hot sambar for a complete meal.',
        ],
    },

    {
        id: 3,
        isLocal: false,
        name: 'Vada Pav',
        description: 'A popular Indian street food with spicy potato vada stuffed inside soft pav.',
        timeToCook: '15 mins',
        serves: 2,
        image: '/vada_pav.png',
        ingredients: [
            'Pav buns : 4',
            'Boiled potatoes : 3 medium',
            'Garlic paste : 1 tsp',
            'Green chilies : 2 finely chopped',
            'Turmeric : 1/2 tsp',
            'Gram flour (besan) : 1 cup',
            'Red chili powder : 1 tsp',
            'Salt : 1 tsp',
            'Oil : for frying',
            'Garlic/Green chutney : as required',
        ],
        steps: [
            'Mash boiled potatoes and mix with spices.',
            'Shape the mixture into round balls.',
            'Prepare a thick besan batter.',
            'Dip potato balls into the batter.',
            'Deep fry until golden and crisp.',
            'Slice pav buns and spread chutney.',
            'Place the hot vada inside the pav.',
            'Press gently to set the filling.',
            'Serve with fried green chilies.',
            'Enjoy hot as a snack or lunch.',
        ],
    },

    {
        id: 4,
        isLocal: false,
        name: 'Ramen Noodles',
        description: 'A warm Japanese noodle bowl with rich broth and flavorful toppings.',
        timeToCook: '45 mins',
        serves: 4,
        video: 'https://youtube.com/embed/6ekYXw-H9l4',
        image: '/ramen_noodles.png',
        ingredients: [
            'Ramen noodles : 4 packs',
            'Chicken broth : 4 cups',
            'Garlic : 4 cloves',
            'Ginger : 1 inch piece',
            'Soy sauce : 3 tbsp',
            'Boiled eggs : 4 halves',
            'Spring onions : 1 cup chopped',
            'Mushrooms : 1 cup sliced',
            'Sesame oil : 1 tbsp',
        ],
        steps: [
            'Simmer garlic, ginger, and soy sauce in broth.',
            'Cook for 20-25 minutes.',
            'Strain the broth.',
            'Boil ramen noodles and drain.',
            'Prepare toppings.',
            'Place noodles in bowls.',
            'Pour hot broth over noodles.',
            'Add toppings neatly.',
            'Drizzle sesame oil.',
            'Serve immediately.',
        ],
    },

    {
        id: 5,
        isLocal: false,
        name: 'Margherita Pizza',
        description: 'A classic Italian pizza topped with cheese, tomatoes, and basil.',
        timeToCook: '25 mins',
        serves: 2,
        image: '/margherita_pizza.png',
        ingredients: [
            'Pizza dough : 1 base',
            'Tomato sauce : 1/2 cup',
            'Mozzarella cheese : 1 cup',
            'Olive oil : 1 tbsp',
            'Fresh basil : 6-8 leaves',
            'Salt : 1/2 tsp',
            'Oregano : 1 tsp',
            'Chili flakes : 1/2 tsp',
        ],
        steps: [
            'Preheat oven to 220°C.',
            'Spread tomato sauce evenly.',
            'Add mozzarella cheese.',
            'Place basil leaves on top.',
            'Drizzle olive oil.',
            'Sprinkle seasoning.',
            'Bake for 10-12 minutes.',
            'Remove from oven.',
            'Slice into pieces.',
            'Serve hot.',
        ],
    },

    {
        id: 6,
        isLocal: false,
        name: 'Chocolate Brownies',
        description: 'Soft, fudgy brownies with rich chocolate flavor.',
        timeToCook: '35 mins',
        serves: 6,
        image: '/chocolate_brownies.png',
        ingredients: [
            'Dark chocolate : 200g',
            'Butter : 100g',
            'Sugar : 1 cup',
            'Flour : 3/4 cup',
            'Cocoa powder : 2 tbsp',
            'Eggs : 2',
            'Vanilla essence : 1 tsp',
            'Salt : a pinch',
        ],
        steps: [
            'Preheat oven to 180°C.',
            'Melt chocolate and butter.',
            'Add sugar and mix.',
            'Add eggs and vanilla.',
            'Sift dry ingredients.',
            'Fold everything together.',
            'Pour into baking tray.',
            'Bake 20-25 mins.',
            'Cool completely.',
            'Cut and serve.',
        ],
    },

    {
        id: 7,
        isLocal: false,
        name: 'Paneer Butter Masala',
        description: 'A creamy and delicious Indian curry made with paneer and butter.',
        timeToCook: '30 mins',
        serves: 3,
        image: '/paneer_butter_masala.png',
        ingredients: [
            'Paneer cubes : 200g',
            'Butter : 2 tbsp',
            'Tomato puree : 1 cup',
            'Cream : 1/4 cup',
            'Onion paste : 1/2 cup',
            'Ginger-garlic paste : 1 tbsp',
            'Red chili powder : 1 tsp',
            'Garam masala : 1/2 tsp',
            'Salt : to taste',
        ],
        steps: [
            'Heat butter in a pan.',
            'Add onion paste and sauté.',
            'Add ginger-garlic paste.',
            'Pour tomato purée.',
            'Add spices.',
            'Add paneer cubes.',
            'Mix cream.',
            'Simmer 5 minutes.',
            'Rest 2 minutes.',
            'Serve hot.',
        ],
    },

    {
        id: 8,
        isLocal: false,
        name: 'Pasta Alfredo',
        description: 'A creamy Italian pasta made with butter, cream, and parmesan.',
        timeToCook: '20 mins',
        serves: 2,
        image: '/pasta_alfredo.png',
        ingredients: [
            'Fettuccine pasta : 250g',
            'Butter : 2 tbsp',
            'Heavy cream : 1 cup',
            'Parmesan cheese : 1/2 cup grated',
            'Garlic : 2 cloves minced',
            'Salt : 1 tsp',
            'Black pepper : 1 tsp',
            'Parsley : 1 tbsp chopped',
        ],
        steps: [
            'Boil pasta until al dente.',
            'Melt butter in a pan.',
            'Add garlic and sauté.',
            'Pour in cream and heat.',
            'Add parmesan and mix.',
            'Season with salt and pepper.',
            'Add cooked pasta.',
            'Mix gently to coat.',
            'Garnish with parsley.',
            'Serve hot.',
        ],
    },

    {
        id: 9,
        isLocal: false,
        name: 'Chicken Tikka',
        description: 'A spicy grilled chicken appetizer popular in Indian cuisine.',
        timeToCook: '35 mins',
        serves: 3,
        image: '/chicken_tikka.png',
        ingredients: [
            'Chicken cubes : 300g',
            'Curd : 1/2 cup',
            'Ginger-garlic paste : 1 tbsp',
            'Turmeric : 1/2 tsp',
            'Red chili powder : 1 tsp',
            'Garam masala : 1/2 tsp',
            'Salt : 1 tsp',
            'Oil : 1 tbsp',
        ],
        steps: [
            'Mix curd and spices in a bowl.',
            'Marinate chicken for 1 hour.',
            'Preheat grill or pan.',
            'Drizzle oil onto surface.',
            'Place marinated chicken.',
            'Cook until brown on all sides.',
            'Check doneness inside.',
            'Remove from heat.',
            'Squeeze lemon on top.',
            'Serve with mint chutney.',
        ],
    },

    {
        id: 10,
        isLocal: false,
        name: 'Cold Coffee',
        description: 'A refreshing chilled coffee drink blended with ice cream.',
        timeToCook: '10 mins',
        serves: 1,
        image: '/cold_coffee.png',
        ingredients: [
            'Milk : 1 cup',
            'Instant coffee : 1 tbsp',
            'Sugar : 2 tbsp',
            'Ice cubes : 5-6',
            'Vanilla ice cream : 1 scoop',
            'Chocolate syrup : 1 tbsp',
        ],
        steps: [
            'Add coffee, sugar, and milk to blender.',
            'Add ice cubes.',
            'Blend until frothy.',
            'Pour into glass.',
            'Add vanilla ice cream.',
            'Drizzle chocolate syrup.',
            'Stir lightly.',
            'Add extra ice if needed.',
            'Serve chilled.',
            'Enjoy the refreshing drink.',
        ],
    },

    {
        id: 11,
        isLocal: false,
        name: 'Veg Fried Rice',
        description: 'A quick stir-fried rice dish with vegetables and soy sauce.',
        timeToCook: '20 mins',
        serves: 2,
        image: '/veg_fried_rice.png',
        ingredients: [
            'Cooked rice : 2 cups',
            'Carrots : 1/4 cup chopped',
            'Beans : 1/4 cup chopped',
            'Capsicum : 1/4 cup chopped',
            'Soy sauce : 1 tbsp',
            'Vinegar : 1 tsp',
            'Salt : 1 tsp',
            'Pepper : 1/2 tsp',
        ],
        steps: [
            'Heat oil in wok.',
            'Add vegetables.',
            'Stir fry 2-3 mins.',
            'Add cooked rice.',
            'Mix gently.',
            'Add soy sauce and vinegar.',
            'Season with salt and pepper.',
            'Toss everything well.',
            'Cook for 2 more mins.',
            'Serve hot.',
        ],
    },

    {
        id: 12,
        isLocal: false,
        name: 'Pancakes',
        description: 'Fluffy breakfast pancakes served with maple syrup.',
        timeToCook: '15 mins',
        serves: 2,
        image: '/pancakes.png',
        ingredients: [
            'Flour : 1 cup',
            'Milk : 3/4 cup',
            'Egg : 1',
            'Sugar : 2 tbsp',
            'Butter : 1 tbsp melted',
            'Baking powder : 1 tsp',
            'Salt : a pinch',
            'Maple syrup : for serving',
        ],
        steps: [
            'Mix dry ingredients.',
            'Add milk and egg.',
            'Whisk to combine.',
            'Add melted butter.',
            'Heat pan and grease lightly.',
            'Pour batter in rounds.',
            'Flip when bubbles appear.',
            'Cook until golden.',
            'Stack on a plate.',
            'Serve with maple syrup.',
        ],
    },
];

export function getAllRecipes() {
    return [...items, ...getLocalRecipes()];
}

